name: Deploy to GH Pages
on:
  push:
    branches:
      - config-deploy
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn ci

      - name: Build project
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Deploy
        run: |
          git init
          git config --global user.email {{ secrets.EMAIL }}
          git config --global user.name {{ secrets.USERNAME }}
          git add -A
          git commit -m 'deploy'
          git push origin config-deploy:gh-pages