name: Deploy to GH Pages

on:
  push:
    branches:
      - config-deploy

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'william-cesar'
        reponame: 'portfolio'
        token: ${{ secrets.GITHUB_TOKEN }}