name: Run Linters

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SO deps
        run: apk add curl bash

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v3
        
      - name: Install packages
        run: yarn ci

      - name: Build application
        run: yarn build

      - name: Run eslint
        run: yarn lint
